apps/dashboard/urls.py
from django.urls import path

from apps.dashboard.views import dashboard, refresh

app_name = "dashboard"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("refresh/", refresh, name="refresh"),
]

django_htmx/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.dashboard.urls")),
]

django_htmx_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.dashboard.urls")),
]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/dashboard/views.py
from django.template.response import TemplateResponse
from django.utils import timezone


def dashboard(request):
    return TemplateResponse(request, "dashboard.html")


def refresh(request):
    context = {
        "now": timezone.now(),
    }
    return TemplateResponse(request, "refresh.html", context)

apps/dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}
  <h1>Dashboard</h1>
  <div id="dashboard">
    <div id="dashboard-content">
      <h2>Dashboard Content</h2>
      <div id="dashboard-alerts"></div>
      <p>This is the dashboard content.</p>
      <button hx-post="{% url 'dashboard:refresh' %}"
        hx-target="#dashboard-alerts"
        hx-swap="outerHTML"
        hx-indicator="#dashboard-alerts"
      >
        Refresh
      </button>
    </div>
  </div>
{% endblock %}

apps/dashboard/templates/refresh.html
<div id="dashboard-alerts">
    <p>Refreshed at {{ now|date:"l, F j, Y - H:i:s" }}</p>
</div>

django_htmx/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A brief description of your page's content goes here." />
    <meta name="keywords" content="keyword1, keyword2, keyword3" />
      <title>
      {% block title %}Django HTMX{% endblock %}
    </title>
    {% block head %}
      <script src="{% static 'js/htmx.min.js' %}"></script>
    {% endblock %}
    {% block extrahead %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

django_htmx_project/templates/base.html
{% load static django_htmx %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A brief description of your page's content goes here." />
    <meta name="keywords" content="keyword1, keyword2, keyword3" />
      <title>
      {% block title %}Django HTMX{% endblock %}
    </title>
    {% block head %}
      <script src="{% static 'js/htmx.min.js' %}" defer></script>
      {% django_htmx_script %}
    {% endblock %}
    {% block extrahead %}{% endblock %}
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block content %}{% endblock %}
  </body>
</html>